import type { Note } from '@/types';

/**
 * A handful of sample notes used for local development.  In the real
 * application these would be generated by summarising uploaded PDFs and
 * retrieved from your backend.  Each note includes a short summary and
 * a longer full text which can be displayed when the user wants to read
 * more.  The `topicId` corresponds with the entries defined in
 * `src/lib/topics.ts`.
 */
export const sampleNotes: Note[] = [
  {
    id: 'note-1',
    title: 'Time and Work Basics',
    summary: 'Understand efficiency, work completion and combined efforts.',
    fullText:
      'This section covers the fundamentals of time and work problems including how to calculate individual and combined rates of doing work. It explores concepts like reciprocal of time and efficiency ratio.',
    topicId: 'time-and-work',
    pdfUrl: '#',
  },
  {
    id: 'note-2',
    title: 'Pipes and Cisterns Overview',
    summary: 'Learn about inflow and outflow problems in tanks.',
    fullText:
      'Pipes and cisterns problems involve understanding rates of filling and emptying containers. This note explains how to determine net rates and the time taken to fill or empty a tank when multiple pipes are involved.',
    topicId: 'pipes-and-cisterns',
    pdfUrl: '#',
  },
  {
    id: 'note-3',
    title: 'Number Series Patterns',
    summary: 'Practice identifying patterns in number sequences.',
    fullText:
      'Number series questions require recognising arithmetic or geometric progressions, Fibonacci sequences and other pattern types. This note provides examples and strategies to deduce the next number in a series.',
    topicId: 'number-series',
    pdfUrl: '#',
  },
];