import { NextRequest, NextResponse } from 'next/server';

/**
 * A simple summarisation endpoint used by the file uploader.  It accepts a
 * multipart/form-data POST request containing a file but, for the purposes
 * of this demonstration, it does not actually parse or analyse the PDF.  It
 * responds with a fixed summary that could be replaced by a call to your
 * backend or a language model.  A GET handler is not provided because
 * summarisation requires a document to be uploaded.
 */

export async function POST(_request: NextRequest) {
  // You could parse the incoming FormData via: const formData = await request.formData()
  // and extract the file: formData.get('file').  Here we ignore the file and
  // return a static summary string for demonstration purposes.
  const summary =
    'This is a placeholder summary generated by the API. In a real scenario this would contain a condensed version of the uploaded note.';
  return NextResponse.json({ summary });
}
